name: 'CodeQL Inject'
description: 'Inject a CodeQL library to customize the default queries to add sources, sinks, taint steps, ...'
inputs:
  patterns:
    description: 'Injection patterns. Each pattern consists of a .qll file and a pattern describing the files (.ql or .qll) to import it to, separated by a colon.'
    required: true
  pack:
    description: 'The pack to inject into'
    required: true
  name:
    description: 'The name of the resulting pack'
    required: true
  version:
    description: 'The version of the modifications (will be added to the version of the pack to be injected to)'
    required: true
  codeql-path:
    description: 'Path of the CodeQL toolchain.'
    required: true
runs:
  using: "composite"
  steps:
    - name: inject
      run: |
        rm -r "$(dirname "${{ inputs.codeql-path }}")/qlpacks"
        python3 \
          "${{ github.action_path }}/action_impl.py" \
          "${{ inputs.codeql-path }}" \
          "${{ inputs.pack }}" \
          "${{ inputs.name }}" \
          "${{ inputs.version }}" \
          "${{ inputs.patterns }}"
      shell: bash
