name: "Manual Injection Test"
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'Name of the pack to publish'
        required: false
        default: 'modified-java-queries-test-manual'
      pack:
        description: 'Base pack (to inject into)'
        required: false
        default: 'codeql/java-queries'
      pattern1:
        description: 'Injection pattern'
        required: false
        default: 'templates/java-customizations.qll:Security/**/*.ql'
      pattern2:
        description: 'Injection pattern'
        required: false
      pattern3:
        description: 'Injection pattern'
        required: false
      pattern4:
        description: 'Injection pattern'
        required: false

jobs:

  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      packages: write
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      id:   codeqltoolchain
      uses: github/codeql-action/init@v1

    - name: codeql-inject
      uses: zbazztian/codeql-inject@main
      with:
        patterns: |
          ${{ github.event.inputs.pattern1 }}
          ${{ github.event.inputs.pattern2 }}
          ${{ github.event.inputs.pattern3 }}
          ${{ github.event.inputs.pattern4 }}
        pack: ${{ github.event.inputs.pack }}
        name: ${{ github.event.inputs.name }}
        codeql-path: ${{ steps.codeqltoolchain.outputs.codeql-path }}
