name: "Ongoing Injection Test"
on:
  schedule:   # run every Monday morning at 9am Bangkok time (2am wherever the machine is running)
    - cron: '0 2 * * 1,2,3,4,5,6'
  push:
    branches: [ main ]

jobs:
  analyze:
    name: Analyze
    runs-on: ubuntu-latest
    permissions:
      packages: write
      actions: read
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Initialize CodeQL
      id:   codeqltoolchain
      uses: github/codeql-action/init@v1

    - name: codeql-inject
      uses: zbazztian/codeql-inject@main
      with:
        patterns: |
          templates/java-customizations.qll:Security/**/*.ql
        pack: codeql/java-queries
        name: zbazztian/modified-java-queries-test-ongoing
        codeql-path: ${{ steps.codeqltoolchain.outputs.codeql-path }}
